GEMINI_API_KEY = "AIzaSyCnJ1LgEdvMlcT5sArTm_TPZ1RwV_8svus"
# Supabase Persistence
SUPABASE_URL = "https://twqskvagxyxexyyjptvk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3cXNrdmFneHl4ZXh5eWpwdHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MDkyMjEsImV4cCI6MjA4NjI4NTIyMX0.D_02DSZMRfKwGvkx9aqhM_4sdF1m6rfioEeaE2uzjhk"
